version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:001090281803:task-definition/account-details-service-xray:2"
        LoadBalancerInfo:
          ContainerName: "account-details-service-xray"
          ContainerPort: "8100"
        PlatformVersion: "LATEST"